### ISSUE TITLE
ability to pull private images?

### ISSUE THREAD

**Issue by djs55** [moby/tool#104]
I tried to add a private image to my .yml file but the `moby build` fails with `Error response from daemon: repository <image> not found: does not exist or no pull access`. If I manually `docker pull <image>:<tag>` it first then it works fine.

I notice the `moby` tool supplies an empty [ImagePullOptions](https://github.com/moby/tool/blob/d87a3f9990ed24ebbb51695879cd640cb07a4b40/src/moby/docker.go#L156) where we could in theory fill in a [PrivilegeFunc](https://github.com/docker/engine-api/blob/4290f40c056686fcaa5c9caf02eac1dde9315adf/types/client.go#L200). I don't know whether the `moby` tool should try to re-use the same mechanisms and credentials as the `docker` CLI or do its own thing.

**Comment by justincormack** [comment]
Yes we should add this. For the moment we should use same login as docker but we may change later.
