### ISSUE TITLE
CONTRIBUTING.md is missed in moby/tool

### ISSUE THREAD

**Issue by arm64b** [moby/tool#108]
We need this file as internal legal approval(for inbound license or agreement for contributions to project), but this file is missed in moby/tool project. Can anyone help us out that?

**Comment by justincormack** [comment]
Sorry, originally this was going to be merged into another repo and we did
not add all the supporting files, will fix this.

Cc @thajeztah

**Comment by arm64b** [comment]
OK, thanks for the update!

**Comment by justincormack** [comment]
The doc has now been added.
