### ISSUE TITLE
runc target os mismatch with current os linux

### ISSUE THREAD

**Issue by davefreitag** [moby/tool#110]
Recent builds of the moby tool aren't working properly with my LinuxKit images. Everything appears to build ok, but when I run the output, all of the containers fail to start. They all fail with errors similar to this:

`FATA[0000] failed to create task      error="rpc error: code = Unknown desc = runtime create failed: runc create failed: target os  mismatch with current os linux" service=rngd`

Screen shot:
![selection_124](https://user-images.githubusercontent.com/20095794/28139219-0d5a2b0e-6719-11e7-9def-cb2da1f2688a.png)

I see the same result with the example yml files in the linuxkit repo. The yml file I'm using here is just the linuxkit.yml file in the base linuxkit/linuxkit directory (swapping tty0 and ttys0 around so I get output in virtualbox):

```
kernel:
  image: linuxkit/kernel:4.9.36
  cmdline: "console=ttyS0 console=tty0"
init:
  - linuxkit/init:14a38303ee9dcb4541c00e2b87404befc1ba2083
  - linuxkit/runc:2310ad9d266cf5d9c4d07613bd2135ed7eb8a21f
  - linuxkit/containerd:c977f27c234d55b85172813b8451f67ea86be4a3
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: binfmt
    image: linuxkit/binfmt:0bde4ebd422099f45c5ee03217413523ad2223e5
  - name: dhcpcd
    image: linuxkit/dhcpcd:4b7b8bb024cebb1bbb9c8026d44d7cbc8e202c41
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:5ab31289889d61a5d2ecbeea8e36ce74ac54737c
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: nginx
    image: nginx:alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/containerd/config.toml
    contents: |
      state = "/run/containerd"
      root = "/var/lib/containerd"
      snapshotter = "io.containerd.snapshotter.v1.overlayfs"
      differ = "io.containerd.differ.v1.base-diff"
      subreaper = false

      [grpc]
      address = "/run/containerd/containerd.sock"
      uid = 0
      gid = 0

      [debug]
      address = "/run/containerd/debug.sock"
      level = "info"

      [metrics]
      address = ":13337"
trust:
  org:
    - linuxkit
    - library
```
Build command is:
`moby -v build -name linuxkit -output dynamic-vhd linuxkit.yml`

I've tried with output types vhd, dynamic-vhd, and vmdk. All produce the same result.

I went through the moby tool git history by commit and built/tested with different versions of the tool.  It starts failing when commit `c3edfec75915d993c76e4a52dcffb4d2278e1da3` was added. All builds before that commit work fine. Any idea what's causing this? Seems like runc is expecting something that doesn't exist.

**Comment by justincormack** [comment]
Sorry yes, someone else just reported this too.

We tried to do a runc update as the spec is being finalized for 1.0 but
after we did the moby part LinuxKit failed, so they are out of sync. It
should be fixed by tomorrow at the latest. If you use an earlier commit, eg
from last week it should be ok. Really sorry about this.

**Comment by davefreitag** [comment]
Ok, sounds good. Thanks!

**Comment by justincormack** [comment]
This should be fixed now, please update your `moby` tool and use the latest linuxkit hashes...
