### ISSUE TITLE
Add support for efi disk

### ISSUE THREAD

**Issue by deitch** [moby/tool#121]
The current tool supports `iso-efi` and `raw`. `raw` works only with bios, while `iso-efi` only works on CD/DVD media (or something that can read it. Booting `iso-efi` off of a flash drive, e.g. will not work. 

We should support EFI bootable disk drives. It can be one of:

* make `iso-efi` bootable as disk (there is a way to do it, not fresh in my mind at the moment but can find it)
* make a new output format `efi-disk` (or `efi-raw`?) that has a drive image with an EFI partition
* make a new output form `efi-disk` (or `efi-raw`?) where the kernel itself is an efi image and thus directly bootable
* some other way?

**Comment by ijc** [comment]
The first option is [Isohybrid](http://www.syslinux.org/wiki/index.php?title=Isohybrid) I believe, it's probably the way to go.

**Comment by deitch** [comment]
> The first option is Isohybrid I believe

**That** was it! Didn't have the energy at the moment to trace it down. Thanks @justincormack 

> it's probably the way to go.

For an immutable distro like linuxkit, which anyways runs as initrd, definitely.

**Comment by justincormack** [comment]
The code for these options is actually in linuxkit (in `tools/`) so maybe make an issue there too.

**Comment by deitch** [comment]
Done.
