### ISSUE TITLE
Optionally add `vmlinux` to output

### ISSUE THREAD

**Issue by rn** [moby/tool#133]
For some kernel debugging, in particular with `perf`, it would be useful to optionally include the uncompressed/unstripped `vmlinux` file to the rootfs if present in the kernel package

**Comment by justincormack** [comment]
I am just working on a platform that boots the `vmlinux`, although I think I should be able to boot the stripped one in this case, but I would like to add some more options here... Is your use case for running the debug kernels?

**Comment by rn** [comment]
I can't remember the details...but I think enabling `CONFIG_KALLSYMS_ALL` might also do the trick.
