### ISSUE TITLE
Create docker image for moby tool

### ISSUE THREAD

**Issue by seemethere** [moby/tool#148]
Is there a docker image for use for the moby tool?

I'm aware that a lot of people are currently building there own from source but it would be nice to have a "semi-official" image to pull from.

**Comment by justincormack** [comment]
There is not an official one no. It would definitely be a good idea. Because it currently needs Docker (this will change later, to make builds easier) it needs either access to a docker socket or use docker-in-docker, so possibly both should be available.

**Comment by xtuc** [comment]
I made https://hub.docker.com/r/xtuc/moby-tool/ if it can help you.

**Comment by justincormack** [comment]
This should be reopened on Linuxkit repo.
