### ISSUE TITLE
Runtime.BindNS.Mnt is not usable

### ISSUE THREAD

**Issue by ijc** [moby/tool#152]
I tried to use `Runtime.Mnt` to make a service's root appear as `/run/mntns/cri` as part of an experiment but trying to use it fails:
```
# nsenter -m/run/mntns/cri ash -l
nsenter: reassociate to namespace 'ns/mnt' failed: Invalid argument
```
I also tries making the mount point a directory (by default it is a file) but that didn't help.

https://stackoverflow.com/questions/34783391/why-i-couldnt-use-mount-bind-proc-pid-ns-mnt-to-another-file-in-ubuntu suggests the bind mounting `/proc/N/ns/mnt` to somewhere is more complicated than the other ns's (thankfully it appears to be unique to mnt namespaces).

**Comment by ijc** [comment]
I had missed some error messages on the console.

In the original case (mounting over a file) it was:
```
ERRO[0001] preparing process                             error="Failed to bind mnt namespace at /run/mntns/cri: invalid argument"
```

and when I tried to make it a directory I actually got:
```
ERRO[0000] preparing process                             error="Cannot create a mount point for namespace bind at /run/mntns/cri: open /run/mntns/cri: is a directory"
```
(because it unconditionally tried to touch the path which failed because the directory already existed).

**Comment by ijc** [comment]
Making the mount point a dir was wrong, but I still haven't managed to figure out who to use the namespace :-(

**Comment by ijc** [comment]
I couldn't figure out how to make this work, but actually all I would have got was a symlink to a `/proc/foo/ns/mnt -> mnt:[4026531840]` type thing when what I actually want/need is `/proc/foo/root` type functionality (i.e. actual visibility into the mount via usual path operations), which would be better served with an ability to configure a path which is linked to `/containers/services/foo/rootfs` (or to otherwise be able to make that path well known).

**Comment by justincormack** [comment]
I suspect this is a `runc` issue. I am not convinced mount namespaces actually work at all in `runc`... it should be a file, it just an inode number, but I can well imagine `runc` doesn't do things right as I don't think it special cases mount namespaces.

What are you trying to do? You should be able to bind mount `/proc/foo/root` but you may not know what `foo` is so it might be a bit inconvenient.

**Comment by ijc** [comment]
The kube project has to pull various stuff (`/opt/cni` is one example) out from containers back into the host filesystem, in order to then allow them to be bound into containers/pods using host binds, which is all a bit ugly and potentially fragile (I hit at least one "race" due to the ordering of bind mounts/moves).

I was hoping to experiment with adding an option to `cri-containerd` to allow me to configure a specific prefix (like `/var/run/moo`) which it would prefix on all host mounts (which are processed by containerd/runc in host context) and then arrange for `/var/run/moo` to point to the root of some container which I would designate as the "pseudo root" container (maybe the cri container, maybe the kubelet container, maybe some dedicated pause container). (kubelet has such an option and requires various tools, like `findmnt` to be present in that root, but it is also hardcoded to `/proc/1` and `/rootfs` in some places, but I can make that more flexible too)

So binding `/proc/foo/ns/mnt` somewhere is actually not useful since it doesn't result in a traversable directory. I could bind `/proc/foo/root` but as you say I may not know `foo` statically.

Hrm, in spelling it all like that it occurs to me that maybe I could have `runtime.mounts` include `{"type": "bind", "source": "/", "destination": "/var/run/moo", "options": ["rw", "bind"]` on my "pseudo-root" container.

**Comment by ijc** [comment]
Thinking about it I'm not sure about the link to `runc` you mention. The bind in question is done by the linuxkit service tool as part of setup, it's not one of the mounts which runc does. I played with `mount` manually from the host namespace and it behaved the same as the error messages from the linuxkit service tool.

`nsenter -m/proc/foo/ns/mnt` does work as expected.

**Comment by justincormack** [comment]
`Runtime.Mnt` is just passed directly to `runc`. We bind mount it to a file yes, but we don't do anything else, so it is just a bind mounted inode, not an actual filesystem you can see.
