### ISSUE TITLE
Ability to use local images

### ISSUE THREAD

**Issue by xtuc** [moby/tool#155]
I would like to "bundle" a local Docker image into my final image. Currently only pulls from public registry is supported: https://github.com/moby/tool/blob/69596e17ddb01fc3d3e75774bffeb760812b2f97/src/moby/image.go#L96

I also tried to use a temporary private registry instead but ended up with: #104.

Relevant comment I found in the source:
https://github.com/moby/tool/blob/69596e17ddb01fc3d3e75774bffeb760812b2f97/src/moby/image.go#L24-L26

Apart from that I don't see any technical restrictions, I hope there isn't some marketing for the public registry involved.

**Edit**:
I have the following error when I'm trying to build the image: `FATA[0032] Failed to extract root filesystem for smth:latest: Could not pull image smth:latest: Trusted pull for smth:latest failed: you are not authorized to perform this operation: server returned 401. `

**Comment by rn** [comment]
I very often use local images only, ie images which are not pushed to hub (or registry). Just make sure your image is not in the `linuxkit` org. Most of the YAMLs in LinuxKit enable content trust so `moby` will talk to the server to check if the image is there and verify the signature. You can also disable the signing with the `-disable-content-trust` option, but generally it's better to use a different hub org for local/non-standard images. For linuxkit package all the makefiles provide a `ORG=foo` and override.

**Comment by xtuc** [comment]
Are you building an image with Linuxkit/moby with your local images? That doesn't seem to work.

My image is trusted (via `trust.images` in the YAML).

**Comment by rn** [comment]
I don't think you can have trust and just use a local image. enabling trust requires image signing to be set up on a notary server for the image etc etc. It's almost certainly not what you want when you want to include a local image in your final assembly.

**Comment by xtuc** [comment]
Ok, I don't want to setup an image signing infrastructure locally (as most user).

What I don't understand is how can you use a local image then? Did you disable the image signing check? Could you maybe share a configuration example that you use?

**Comment by rn** [comment]
have you tried removing the `trust.image` line in the YAML? That tells `moby` to enable content trust for that image. Also, have you tried `-disable-content-trust` on `moby build`?

**Comment by ijc** [comment]
FWIW my MO is to build packages I'm hacking on with `make -C /path/to/pkg ORG=ijc HASH=dev tag` and then replace `linuxkit/pkg:HASH` with `ijc/pkg:dev` in the yml files I am working with (my different dev branches generally have a commit in them doing that). Since `ijc` is not listed in any `trust` section in any yml file they are never checked for trust.

Strictly speaking my actual hub user/org is `ijc25` (because it needs to be 4 characters) but I'm too lazy to type that most of the time ;-) and it doesn't matter because I never want to push any of my development stuff there.

**Comment by xtuc** [comment]
`-disable-content-trust` seems to work fine, thanks.

My Docker image is over 1Gb and it seems to hit some size limit: `FATA[0107] Error writing outputs: Error writing raw output: fork/exec /home/RobPike/go/bin/linuxkit: cannot allocate memory`. Do you have any pointers about that?

I need to reduce the size of my image anyway.

**Comment by xtuc** [comment]
I'm closing this, thanks for your help!
