### ISSUE TITLE
allow and an output directory to be specified during build

### ISSUE THREAD

**Issue by dave-tucker** [moby/tool#17]
It would be nice to be able to `moby build -o ./_build linuxkit.yml` and have the output nicely contained in a folder instead of the `pwd`.

My use case is for CI and testing of LinuxKit... where I want to build a `yml` file and place the output in a common directory that can be accessed by other tests.

**Comment by rneugeba** [comment]
`-name` kinda does this:
```
moby build -name ~/tmp/foo linuxkit
```

**Comment by dave-tucker** [comment]
If that works, then great. I guess the help text should be updated... or `--name` and `--output-directory` could be split to make it clearer which part of the path is being manipulated

**Comment by justincormack** [comment]
See #47 for PR implementing this
