### ISSUE TITLE
Linking packages to the source (plus package/image tagging)

### ISSUE THREAD

**Issue by rn** [moby/tool#20]
## Terminology
- `package`: A moby package stored on hub
- `repository`: Source code repository (not hub repository)
- `digest`: The docker image digest, ie the SHA256
- `git hash`: The hash/id of a commit (`git rev-parse HEAD`)
- `git tree hash`: The content hash of a given directory, e.g `git rev-parse HEAD:../$(notdir $(CURDIR))` in `make`
- `git tag`: The tag of the current `HEAD` if any, ie `git describe --exact-match HEAD`
(note, we are using `git` here, but the proposal should be equally applicable to other modern source control systems, like mercurial.

## Problem
The moby packages generated and used in LinuxKit currently use a unique content hash of the *source files* used to build the package (mostly the git tree hash) as a tag to uniquely identify package versions. We can't use the docker image digest as the builds are not 100% reproducible because the binaries may contain things like build time stamps etc.

We will likely extend this to also use version numbers in tags once we do releases. However for package builds in between releases we still want to use content hashes. We use content hashes (git subtree hashes) to check if we need to rebuild a package, ie if none of the files used to build the package have changed there is not need to rebuild and push a new version. However, we currently have no good and simple way to link a given package to a source code repository and a specific commit in that repository.

## Proposal
We assume, though it is not essential, that packages, by default are tagged with the `git tree hash` (or some other hash), but *not* with the `git hash`. The `git hash` changes with every commit, ie commits which may not affect the contents of a package.

We propose to store the `repository` and the `git hash` in labels in the package, specifically under `org.mobyproject.repository` and `org.mobyproject.commit`. Note, that this affects the `digest` of the package. 

Then, by inspecting the package (`docker inspect`), we can extract the `repository` and the `git hash` and thus directly link it to a specific version.

To build a package, we first need to check if the package tagged with the tree hash already exist, and only build it if it doesn't already exist. A package is always tagged and pushed with the tree hash.

If we tag a release in the repository, we can simply pull the package based on git tree hash, retag the package with the release tag and push the re-tagged package to hub. This does not affect the digest, nor the git commit stored in the image, so we can easily check if an image changed between releases.

An alternative proposal is to add the `git hash` (and possibly the repository) as notary metadata.

**Comment by ijc25** [comment]
One use case I have is that having noticed that `linuxkit.yml` had `linuxkit/init:f71c3b30ac1ba4ef16c160c89610fa4976f9752f` while `projects/swarmd/swarmd.yml` had `linuxkit/init:42fe8cb1508b3afed39eb89821906e3cc7a70551` I wanted to be able to answer the question "what would I get if I upgraded", being able to find the git sha of each of those would have allowed me to do so.

**Comment by rneugeba** [comment]
there is also https://github.com/opencontainers/image-spec/blob/master/annotations.md#rules
which pretty much contains the info we need (and some other)

**Comment by justincormack** [comment]
Once the linuxkit makefile gets turned into a general tool this will be available elsewhere, linuxkit is providing the prototype
