### ISSUE TITLE
Enable 'moby build' for private repos

### ISSUE THREAD

**Issue by rn** [moby/tool#202]
Currently `moby build` fails with:
```
FATA[0008] Failed to build init tarball from foo/bar:123: Could not pull image foo/bar:123: Error response from daemon: pull access denied for foo/bar, repository does not exist or may require 'docker login'
```
where `foo/bar` is a private repo on hub and I can `docker pull` is manually.

Looks like the `moby build` is not using authentication.

**Comment by djs55** [comment]
Also reported as #104

**Comment by rn** [comment]
I had a quick look at this, and it seems that we'd need to vendor in `github.com/docker/cli` and then:
1) use something like `GetDefaultAuthConfig()` for each registry we might pull from. This will look up credentials from the credidentials store (or `config.json`
2) call `client.RegistryLogin()` in the code in `dockerClient()` or elsewhere.
