### ISSUE TITLE
Archive this repo with link to linuxkit?

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/tool#220]
Can we make this repo read-only archive, as the tool has moved to linuxkit repo?

cc @justincormack @rn @cpuguy83 @thaJeztah

**Comment by thaJeztah** [comment]
SGTM

**Comment by justincormack** [comment]
Yes, I was planning to move any relevant issues, but could close and archive first....

**Comment by justincormack** [comment]
PR in #221
