### ISSUE TITLE
Use Docker API to run breaks ISO creation

### ISSUE THREAD

**Issue by chanwit** [moby/tool#28]
This commit: bb7cbcef40c4ae1d848b8a5c8225060c31b125a7
is pretty much breaking when `moby build` an ISO for both bios and efi.

It results in a 0-size iso file.

**Comment by riyazdf** [comment]
oops, sorry about that!  I'm looking into the issue now :)  Seems like this is a non issue for `kernel+initrd` but not for other outputs.

Might be helpful if we could hook this repo's PRs up to tests

**Comment by riyazdf** [comment]
hmm...looks like the hijacked response from the ISO image is returning this error:
```
/mv: can't rename '': No such file or directory
```

So it seems that the input being piped in to the container is not being recognized as its proper tar and we're hitting [this error](https://github.com/linuxkit/linuxkit/blob/master/tools/mkimage-iso-bios/make-iso#L19-L20) - I'm debugging the proper way to send over the stdin data

**Comment by chanwit** [comment]
Thank you for tackling this one @riyazdf !!

**Comment by erick-thompson** [comment]
I'm still running into this issue when creating a iso-efi. I started bits cloned this morning, so I'm not sure if the fix above is still in-flight, or if there is another issue. 

`FATA[0017] Error writing outputs: Error writing iso-efi output: exit status 1: mv: can't rename '': No such file or directory`

This is running moby on Windows 10 against the docker.yml. Everything works up to the create outputs step.

**Comment by riyazdf** [comment]
@erick-thompson hm - not sure what's going on there, the fix above should be complete (it was just a full revert).  We have a test case against [this yml](https://github.com/linuxkit/linuxkit/blob/master/test/cases/000_build/000_outputs/test.yml) for building iso-efi, could you try that one? 

I'll continue to investigate, my hunch is there's an issue with the `linuxkit/mkimage-iso-efi` image

**Comment by justincormack** [comment]
Maybe there is a Windows specific issue? CI is only testing build on Linux,
something could have been missed with the filename code.
