### ISSUE TITLE
error undefined: x509.SystemCertPool

### ISSUE THREAD

**Issue by zjsyhjh** [moby/tool#42]
I use `go get -u github.com/moby/tool/cmd/moby` to install `moby` tool but find something error.

`goproject/src/github.com/moby/tool/cmd/moby/trust.go:186: undefined: x509.SystemCertPool`

OS distribution
`CentOS Linux release 7.3.1611 (Core)`

go version
`go version go1.6.3 linux/amd64`

**Comment by justincormack** [comment]
I guess that `x509.SystemCertPool` was probably added in Go 1.7, and you will need a more recent Go version.

**Comment by zjsyhjh** [comment]
@justincormack yes. I replace it with Go 1.8, and install `moby` successfully.
