### ISSUE TITLE
Command line override for content trust

### ISSUE THREAD

**Issue by rneugeba** [moby/tool#55]
If the YAML file specifies `trust` for specific images or all images from an org, it is harder for developers to test locally modified packages. It'll also be harder for CI systems which would push packages from a PR to a local registry to test them.

I think it would be good to add a way to globally disable content trust checks for builds.

**Comment by riyazdf** [comment]
I propose we do something along the lines of the docker flag: `--disable-content-trust` and default to `false`

Open question is whether we want just a single flag for global control, or also per-image/org flags?
`--disable-content-trust=true` # turn off all trust checks for this build
`--disable-content-trust-image=<image_name>` # turn off trust checks just for `<image_name>`
`--disable-content-trust-org=<org_name>` # turn off trust checks for all images in the `<org_name>` org

**Comment by rneugeba** [comment]
that would work. Thanks

**Comment by justincormack** [comment]
I think a single flag is suficient - if you dont want the detailed checks, just edit the file, this is for debug only
