### ISSUE TITLE
trust failure has unhelpful message

### ISSUE THREAD

**Issue by justincormack** [moby/tool#64]
Pulling an unsigned image when you have said you only want signed returns a very generic 401 error, it should specifically say the image is not signed, preferably with more details eg once we anable pinning.

cc @deitch who reported this

```
Pull image: linuxkit/compose-dynamic-example:de453299b70435f19372dc0b983d018a9501bc72
FATA[0148] Failed to extract root filesystem for linuxkit/compose-dynamic-example:de453299b70435f19372dc0b983d018a9501bc72: Could not pull image linuxkit/compose-dynamic-example:de453299b70435f19372dc0b983d018a9501bc72: Trusted pull for linuxkit/compose-dynamic-example:de453299b70435f19372dc0b983d018a9501bc72 failed: you are not authorized to perform this operation: server returned 401.
make: *** [dynamic] Error 1
```
cc @riyazdf

**Comment by riyazdf** [comment]
@justincormack ah - this is related to the auth system behind the deployed notary server because this repo does not exist in Docker Hub or its Notary Server: https://hub.docker.com/r/linuxkit/compose-dynamic-example/.

cc'ing some of the notary folks for a heads up: @cyli @dlawrence

**Comment by justincormack** [comment]
Oh I see, yes it's normal to return 401 if it might exist but be private
