### ISSUE TITLE
'moby build -hyperkit' doesn't work

### ISSUE THREAD

**Issue by dave-tucker** [moby/tool#68]
I was excited to try a `moby build -hyperkit` 😁 

I was upset to see it ignored and qemu was used instead 😕 

I was even more confused to see that the `hyperkit bool` is completely ignored https://github.com/moby/tool/blob/master/cmd/moby/linuxkit.go#L129 😖 

It'd be nicer to warn the user if it isn't supported or perhaps drop the flag until such time as it's implemented.

**Comment by justincormack** [comment]
It did work for a while, but now needs support for multiple disks in the
hyperkit Go API to make it work.
