### ISSUE TITLE
ability to override the images in a configuration file

### ISSUE THREAD

**Issue by dave-tucker** [moby/tool#95]
It would be useful to be able to override the images that are specified in a config file.

In linuxkit, we want to do this in order to test changes to a package without having to manually update our growing number of configuration files.

It was suggested in https://github.com/linuxkit/linuxkit/pull/2003#issuecomment-307161596 that an additional YAML file with the following format could be used to acheive this.
```
- source: linuxkit/dhcpcd
  substitute: linuxkitci/dhcpcd:testbuildhash
```

I've started an implementation (which I'll push shortly) that implements the above and makes the following assumptions:
1) The file will always be called `override.yml`
2) The `override.yml` is always specified *after* the main configuration file

If it's agreed that this feature is useful I'll be happy to update the implementation according to any design desicions that are made in this thread.

**Comment by justincormack** [comment]
It should definitely not be required to be called `override.yaml` - it should just be part of the config, whether it happens to get that via one or more yaml files is an implementation detail - the data structure is the core thing yaml files are not first class.

**Comment by justincormack** [comment]
It should just be a section called `overrides` or something like that.

**Comment by dave-tucker** [comment]
@justincormack ack. that sounds sensible. I've reworked the PR accordingly.

**Comment by MagnusS** [comment]
This could be useful when building editions as well. E.g. for docker for mac we will have to replace the open docker-ce with one that includes custom components. 

It seems that adding another service with the same name in the next yml will also override the first one currently. This could also be useful, but not sure if it's officially supported?

**Comment by MagnusS** [comment]
Hm actually, it looks like both images are included in the same rootfs if you use the same name

**Comment by justincormack** [comment]
Should be reopened in linuxkit repo
